matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd inv_trans_tool
      install:
        - pip install pipenv
        - pipenv install
      script: pipenv run pytest

    - language: python
      python: 3.6
      before_script:
        - cd monitor_api
      install:
        - pip install pipenv
        - pipenv install
      script: pytest
