#!/usr/bin/env python3
""" Tests for jopling """

from typing import Dict, List

# fmt: off
issues:List[Dict] = [
    {"Summary": "Grid with multiple data/domain object instances", "Issue key": "DROOLS-3095", "Issue id": "12773656", "Issue Type": "Task", "Status": "Resolved", "Project key": "DROOLS", "Project name": "Drools", "Project type": "software", "Project lead": "mfusco", "Project description": "The Drools project.", "Project url": "http://example.com", "Priority": "Major", "Resolution": "Done", "Assignee": "gabriolo", "Reporter": "gabriolo", "Creator": "gabriolo", "Created": "10/Oct/18 6:03 AM", "Updated": "05/Nov/18 4:05 AM", "Last Viewed": "29/Oct/19 12:29 PM", "Resolved": "05/Nov/18 4:05 AM", "Affects Version/s": "", "Fix Version/s": "", "Component/s": "Scenario Simulation and Testing", "Due Date": "", "Votes": "0", "Labels": "", "Description": "As user I want to use multiple instances of my DO in a test scenario.\r\n\r\n*Implementation specs:*\r\nImplement \"Instance\" concept on the GIVEN/EXPECTED columns.\r\nGiven/Expected columns should have three headers: \r\n# the top one is the group (GIVEN/EXPECTED),\r\n#  the second one is the actual instance of a given type (ex Person1, Person2, Dispute)\r\n# the third one is the specific property of the instance.\r\nBelow every instance header there could be one ore more property header - each of them belonging to that instance.\r\n\r\nThe workflow to define template creation is going to change because of the new header level:  the user may define the type/name of the instance *before* mapping the final properties, *OR* s/he may define directly a property, in which case the instance is automatically inferred and populated.\r\n\r\nWhen clicking on a GIVEN \"Instance\" header, user should see only first-level data objects in the right panel.\r\nWhen clicking on an EXPECT \"Instance\" header, user should see only first-level data objects in the right panel *AND* the GIVEN instances.\r\n\r\nWhen clicking on a Property header, *if* the instance is already defined, user should see only first-level properties of the instance it belongs to; *otherwise* s/he should see every properties of every data objects. \r\n\r\nChanging Instance type is not allowed (dose not makes sense): only \"DELETE\" is possible at \"Instance\" level. Deleting an Instance header(column) recursively delete all the properties.\r\n\r\nThese issue is related to http://example.com/browse/DROOLS-2788", "Environment": "", "Original Estimate": "", "Remaining Estimate": "", "Time Spent": "", "Work Ratio": "", "Security Level": "", "Outward issue link (Causality)": "", "Outward issue link (Dependency)": "", "Outward issue link (Related)": "", "Attachment": "", "Sprint": "", "Comment": ""},
    {"Summary": "[DMN Editor] Add support to define data-types", "Issue key": "DROOLS-2563", "Issue id": "12751006", "Issue Type": "Epic", "Status": "Resolved", "Project key": "DROOLS", "Project name": "Drools", "Project type": "software", "Project lead": "mfusco", "Project description": "The Drools project.", "Project url": "http://example.com", "Priority": "Major", "Resolution": "Done", "Assignee": "karreiro", "Reporter": "manstis", "Creator": "manstis", "Created": "18/May/18 9:51 AM", "Updated": "05/Nov/18 7:29 AM", "Last Viewed": "29/Oct/19 12:29 PM", "Resolved": "05/Nov/18 6:24 AM", "Affects Version/s": "", "Fix Version/s": "", "Component/s": "DMN Editor", "Due Date": "", "Votes": "0", "Labels": "drools-tools", "Description": "As a practitioner, I want to be able to define Data Types in the UI, so that when the DMN engine evaluates a decision table input/output it will check if the type of the value matches the specified type. \r\n\r\nVerification conditions:\r\nSupport added for the User to define data-types ({{ItemDefinition}}).\r\n\r\nThis may become a top-level task when I get to work on it; as the requirement is quite large and encompasses nested data-types (a whole new grid will be required); and definition of enums, constrains on values etc.", "Environment": "", "Original Estimate": "", "Remaining Estimate": "", "Time Spent": "", "Work Ratio": "", "Security Level": "", "Outward issue link (Causality)": "", "Outward issue link (Dependency)": "", "Outward issue link (Related)": "", "Attachment": "", "Sprint": "2018 Week 45-47", "Comment": "11/Jul/18 11:02 AM;uxdlc;[~jomarko] Or just changing it works for me, thank you! :)"},
    {"Summary": "[MDC] Implement notifications in UI", "Issue key": "AEROGEAR-7964", "Issue id": "12771753", "Issue Type": "Task", "Status": "Resolved", "Project key": "AEROGEAR", "Project name": "AeroGear", "Project type": "software", "Project lead": "weil", "Project description": "Mobile Services", "Project url": "http://example.com", "Priority": "Major", "Resolution": "Done", "Assignee": "jhellar", "Reporter": "jhellar", "Creator": "jhellar", "Created": "27/Sep/18 5:10 AM", "Updated": "05/Nov/18 3:41 AM", "Last Viewed": "29/Oct/19 12:29 PM", "Resolved": "05/Nov/18 3:41 AM", "Affects Version/s": "", "Fix Version/s": "", "Component/s": "", "Due Date": "", "Votes": "0", "Labels": "team-service-2", "Description": "Currently in OpenShift when some operation is started, finished or failed, UI informs user about that with notifications. This should be implemented also in Mobile Developer Console UI.\r\n\r\nOne example is deletion of build config - currently if deletion fails in MDC, there is no notification about that for user.\r\n\r\nNotifications for all relevant events should be added. To get an idea of what notifications we should implement, try to do CRUDL operations on all mobile related resources in OpenShift and look for notifications. ", "Environment": "", "Original Estimate": "", "Remaining Estimate": "", "Time Spent": "", "Work Ratio": "", "Security Level": "", "Outward issue link (Causality)": "", "Outward issue link (Dependency)": "", "Outward issue link (Related)": "AEROGEAR-8047", "Attachment": "", "Sprint": "", "Comment": ""},
    {"Summary": "", "Issue key": "", "Issue id": "", "Issue Type": "", "Status": "", "Project key": "", "Project name": "", "Project type": "", "Project lead": "", "Project description": "", "Project url": "", "Priority": "", "Resolution": "", "Assignee": "", "Reporter": "", "Creator": "", "Created": "", "Updated": "", "Last Viewed": "", "Resolved": "", "Affects Version/s": "", "Fix Version/s": "", "Component/s": "", "Due Date": "", "Votes": "", "Labels": "", "Description": "", "Environment": "", "Original Estimate": "", "Remaining Estimate": "", "Time Spent": "", "Work Ratio": "", "Security Level": "", "Outward issue link (Causality)": "", "Outward issue link (Dependency)": "", "Outward issue link (Related)": "", "Attachment": "", "Sprint": "", "Comment": ""}
]
# fmt: on


def test_nothing():
    pass
