# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Wed Mar 13 14:45:53 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.screens = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screens.sizePolicy().hasHeightForWidth())
        self.screens.setSizePolicy(sizePolicy)
        self.screens.setObjectName("screens")
        self.signin_page = QtWidgets.QWidget()
        self.signin_page.setObjectName("signin_page")
        self.formLayoutWidget = QtWidgets.QWidget(self.signin_page)
        self.formLayoutWidget.setGeometry(QtCore.QRect(170, 120, 211, 89))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.splitter = QtWidgets.QSplitter(self.formLayoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.id_edit = QtWidgets.QLineEdit(self.splitter)
        self.id_edit.setObjectName("id_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.formLayoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.pwd_edit = QtWidgets.QLineEdit(self.splitter_2)
        self.pwd_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_edit.setObjectName("pwd_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(self.formLayoutWidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.sign_in_button = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_in_button.sizePolicy().hasHeightForWidth())
        self.sign_in_button.setSizePolicy(sizePolicy)
        self.sign_in_button.setObjectName("sign_in_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.splitter_3)
        self.screens.addWidget(self.signin_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_0.setObjectName("horizontalLayout_0")
        self.label_si = QtWidgets.QLabel(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_si.sizePolicy().hasHeightForWidth())
        self.label_si.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_si.setFont(font)
        self.label_si.setObjectName("label_si")
        self.horizontalLayout_0.addWidget(self.label_si)
        self.signed_in_as_label = QtWidgets.QLabel(self.main_page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.signed_in_as_label.setFont(font)
        self.signed_in_as_label.setObjectName("signed_in_as_label")
        self.horizontalLayout_0.addWidget(self.signed_in_as_label)
        self.verticalLayout.addLayout(self.horizontalLayout_0)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label_4 = QtWidgets.QLabel(self.main_page)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_1.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.activity_table = QtWidgets.QTableWidget(self.main_page)
        self.activity_table.setObjectName("activity_table")
        self.activity_table.setColumnCount(0)
        self.activity_table.setRowCount(0)
        self.activity_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.activity_table)
        self.screens.addWidget(self.main_page)
        self.gridLayout.addWidget(self.screens, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWhat = QtWidgets.QAction(MainWindow)
        self.actionWhat.setObjectName("actionWhat")
        self.version_info = QtWidgets.QAction(MainWindow)
        self.version_info.setEnabled(False)
        self.version_info.setObjectName("version_info")

        self.retranslateUi(MainWindow)
        self.screens.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Monitor tool", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Id", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Password", None, -1))
        self.sign_in_button.setText(QtWidgets.QApplication.translate("MainWindow", "Sign In", None, -1))
        self.label_si.setText(QtWidgets.QApplication.translate("MainWindow", "Signed in as: ", None, -1))
        self.signed_in_as_label.setText(QtWidgets.QApplication.translate("MainWindow", "no one", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Filter:", None, -1))
        self.actionWhat.setText(QtWidgets.QApplication.translate("MainWindow", "What", None, -1))
        self.version_info.setText(QtWidgets.QApplication.translate("MainWindow", "[Inv_Trans] Monitor tool v", None, -1))

