"""Add tools table

Revision ID: c13ac1b320b7
Revises: 1f136811cab5
Create Date: 2020-07-29 14:33:55.171116

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c13ac1b320b7"
down_revision = "1f136811cab5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tools",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    with op.batch_alter_table("data_access_policies", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk__data_access_policies__tool__tools", "tools", ["tool"], ["name"]
        )

    with op.batch_alter_table("data_accesses", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk__data_accesses__tool__tools", "tools", ["tool"], ["name"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_accesses", schema=None) as batch_op:
        batch_op.drop_constraint("fk__data_accesses__tool__tools", type_="foreignkey")

    with op.batch_alter_table("data_access_policies", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk__data_access_policies__tool__tools", type_="foreignkey"
        )

    op.drop_table("tools")
    # ### end Alembic commands ###
